"""added address,count

Revision ID: 47e64ca4bc07
Revises: 43e247adce64
Create Date: 2025-03-12 14:34:06.586475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e64ca4bc07'
down_revision = '43e247adce64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=30), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('customer_location', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('customer_email', sa.String(length=50), nullable=False),
    sa.Column('customer_address', sa.String(length=100), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['delivery_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('count')

    op.drop_table('product_size')
    op.drop_table('order')
    # ### end Alembic commands ###
