"""changed databases schema

Revision ID: 4b94687370d3
Revises: 
Create Date: 2025-02-26 22:59:38.134268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b94687370d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('size_small')
        batch_op.drop_column('size_large')
        batch_op.drop_column('size_medium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_medium', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('size_large', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('size_small', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))

    op.drop_table('product_size')
    # ### end Alembic commands ###
